services:
  db:
    image: postgres:16
    container_name: sfs_postgres
    environment:
      POSTGRES_DB: sfsdb
      POSTGRES_USER: sfsuser
      POSTGRES_PASSWORD: sfspassword
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: mcloots/mich-sfs-api:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: Host=db;Port=5432;Database=sfsdb;Username=sfsuser;Password=sfspassword
      ALLOWED_ORIGINS: http://localhost:4200
    ports:
      - '6007:8080'
    depends_on:
      - db

  frontend:
    image: mcloots/mich-sfs-client:latest
    ports:
      - '4200:80'
    depends_on:
      - api

volumes:
  db_data:
